doctrine:
    dbal:
        #host: '//127.0.0.1/%env(resolve:PGDATABASE)%?charset=utf8&unix_socket=%env(resolve:PGHOST)%'
        host: 'localhost'
        unix_socket: '%env(resolve:MYSQL_DATA)%/mysqld.sock'
        user: '%env(resolve:MYSQL_USER)%'
        password: '%env(resolve:MYSQL_PASSWORD)%'
        dbname: '%env(resolve:MYSQL_DATABASE)%'
        driver: 'pdo_mysql'
        #driver_class: PgSQLSocketDriver
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '10'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
